---
- name: waiting for a few seconds to let the machine start
  pause:
    seconds: 10
- name: Coptying the ssh file on the jump server for accessing private VMs
  command: 'scp -i hackathon_success_key.pem hackathon_success_key.pem ubuntu@{{ pub_instance_status.instances[0].public_ip }}:/home/ubuntu -y' 

