---
- name: Create local account VPC peering Connection
  ec2_vpc_peer:
    region: "{{ region }}"
    vpc_id: "{{ec2_vpc_1_result.vpc.id }}"
    peer_vpc_id: "{{ec2_vpc_2_result.vpc.id }}"
    state: present
    tags:
      Name: Hackathon_VPC_peering_CIC-I-Team1_
  register: vpc_peer

- name: Accept local VPC peering request
  ec2_vpc_peer:
    region: "{{ region }}"
    peering_id: "{{ vpc_peer.peering_id }}"
    state: accept
  register: accepting_peer

- name: create route table for vpc_1 peering
  ec2_vpc_route_table:
    vpc_id: "{{ ec2_vpc_1_result.vpc.id }}"
    region: "{{ region }}"
    tags:
       Name: "{{ route_table_1_name }}"
    subnets: [ "{{ subnet_pub_sub_1_result.subnet.id }}" ]   
    routes:
       - dest: "{{ cidr_traffic_range }}"
         gateway_id: "{{ igw_1_result.gateway_id }}"
       - dest: "{{ cidr_vpc2_range }}"
         gateway_id: "{{ vpc_peer.peering_id }}"
  register: peering_RT_VPC1
  
  
- name: create route table for vpc_2 peering
  ec2_vpc_route_table:
    vpc_id: "{{ ec2_vpc_2_result.vpc.id }}"
    region: "{{ region }}"
    tags:
       Name: "{{ route_table_2_name }}"
    subnets: [ "{{ subnet_prv_sub_2_result.subnet.id }}" ]   
    routes:
       - dest: "{{ cidr_traffic_range }}"
         gateway_id: "{{ nat_gateway.nat_gateway_id }}"
       - dest: "{{ cidr_vpc1_range }}"
         gateway_id: "{{ vpc_peer.peering_id }}"
       
         
  register: peering_RT_VPC2
#- name: waiting for a few seconds to let the machine start
#  pause:
#    seconds: 5  

#- name: Copying the ssh file on the jump server for accessing private VMs
#  command: 'scp -i hackathon_success_key.pem hackathon_success_key.pem ubuntu@{{ pub_instance_status.instances[0].public_ip}}:/home/ubuntu'

