---
- name: creating route table in VPC1
  ec2_vpc_route_table:
      vpc_id: "{{ ec2_vpc_1_result.vpc.id }}"
      region: "{{ region }}"
      state: present
      tags:
         Name: "{{ route_table_1_name }}"
      subnets: [ "{{ subnet_pub_sub_1_result.subnet.id }}" ]
      routes:
         - dest: "{{ cidr_traffic_range }}"
           gateway_id: "{{ igw_1_result.gateway_id }}"
  register: public_RT_VPC1
- debug:
    msg: "{{ public_RT_VPC1.route_table.id }}"

- name: creating route table in VPC2
  ec2_vpc_route_table:
      vpc_id: "{{ ec2_vpc_2_result.vpc.id }}"
      region: "{{ region }}"
      state: present
      tags:
         Name: "{{ route_table_2_name }}"
      subnets: [ "{{ subnet_prv_sub_2_result.subnet.id }}" ]
      routes:
         - dest: "{{ cidr_traffic_range }}"
           gateway_id: "{{ nat_gateway.nat_gateway_id }}"
  register: private_RT_VPC2

- debug:
    msg: "{{ private_RT_VPC2.route_table.id }}"

  



