---
- name: launce ec2 instance in VPC1
  ec2:
    instance_type: t2.micro
    image: "{{ ubuntu_machine_image }}" 
    count: 1
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ subnet_pub_sub_1_result.subnet.id }}"
    group: "{{ security_group_1_results.group_name }}"
    wait: yes
    instance_tags:
       Name: Bastion_HI-HACKATHON-CIC-I-Team1
       Env: Dev
  register: pub_instance_status

- debug:
    msg: "{{ pub_instance_status.instances[0].public_ip }}"

- name: waiting for a few seconds to let the machine start
  pause:
     seconds: 15

- name: Coptying the ssh file on the jump server for accessing private VMs    
  command: 'scp -i hackathon_success_key.pem hackathon_success_key.pem ubuntu@{{ pub_instance_status.instances[0].public_ip }}:/home/ubuntu'
- name: launce ec2 instance in VPC2
  ec2:
    instance_type: t2.micro
    image: "{{ ubuntu_machine_image }}"
    count: 1  
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    vpc_subnet_id: "{{ subnet_prv_sub_2_result.subnet.id }}"
    group: "{{ security_group_2_results.group_name }}"
    wait: yes
    instance_tags:
       Name: Ec2-VPC2_HI-HACKATHON-CIC-I-Team1
       Env: Dev
  register: prv_instance_status

- debug:  
    msg: "{{ prv_instance_status.instances[0].private_ip }}"

    

