---
- name: create ec2 vpc first public_subnet for vpc-1
  ec2_vpc_subnet:
    vpc_id: "{{ ec2_vpc_1_result.vpc.id }}"
    region: "{{ region }}"
    az: "{{ zone }}"     
    state: present
    cidr: "{{ sub_pub_1_cidr }}"
 # enabling public ip
    map_public: yes
    resource_tags:
        Name: "{{ Hackathon_subnet_public_1 }}"
  register: subnet_pub_sub_1_result

  
- name: create ec2 vpc second public_subnet for vpc-2
  ec2_vpc_subnet:
    vpc_id: "{{ ec2_vpc_2_result.vpc.id }}"
    region: "{{ region }}"
    az: "{{ zone }}"     
    state: present
    cidr: "{{ sub_pub_2_cidr }}"
 # enabling public ip
    map_public: yes
    resource_tags:
        Name: "{{ Hackathon_subnet_public_2 }}"
  register: subnet_pub_sub_2_result      
        
- name: create ec2 vpc first private_subnet for vpc-1
  ec2_vpc_subnet:
    vpc_id: "{{ ec2_vpc_1_result.vpc.id }}"
    region: "{{ region }}"
    az: "{{ zone }}"     
    state: present
    cidr: "{{ sub_prv_1_cidr }}"
    resource_tags:
        Name: "{{ Hackathon_subnet_private_1 }}"
  register: subnet_prv_sub_1_result

  
- name: create ec2 vpc second private_subnet for vpc-2
  ec2_vpc_subnet:
    vpc_id: "{{ ec2_vpc_2_result.vpc.id }}"
    region: "{{ region }}"
    az: "{{ zone }}"     
    state: present
    cidr: "{{ sub_prv_2_cidr }}"
    resource_tags:
        Name: "{{ Hackathon_subnet_private_2 }}"
  register: subnet_prv_sub_2_result    
