---
- name: Playbook to 
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - creating_vpc
    - creating_igw
    - creating_subnets
    - security_group
    - nat-gateway
    - creating_route_tables
    - creating_pemkey
#    - launch_ec2
    - vpc_peering
