---
- name: Playbook to use Ansible roles for creating ec2 bastion and related resources
  hosts: localhost
#  become: true
  connection: local
  gather_facts: false
  roles:
    - creating_vpc
    - creating_igw
    - creating_subnets
    - security_group
    - nat-gateway
    - creating_pemkey
    - launch_ec2
    - vpc_peering_n_route_table
    - copy_key
